name: Node.js CI/CD with Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        echo "Checking for package-lock.json"
        if [ -f package-lock.json ]; then
          echo "Using existing package-lock.json"
          npm ci
        else
          echo "No package-lock.json found, using npm install"
          npm install
        fi

    - name: Run Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        output: results.sarif
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 0
        upload: true
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
