name: Node.js CI

# Trigger the workflow when pushing to main or opening pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ensure to match the node version in package.json

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run ESLint to check code quality
    - name: Run ESLint
      run: npm run lint  # Runs "eslint ." as per the script in package.json

    # Step 5: Install Codacy CLI (used to trigger Codacy scan)
    - name: Install Codacy CLI
      run: npm install -g codacy-coverage

    # Step 6: Trigger Codacy Code Coverage
    - name: Upload code coverage to Codacy
      run: |
        codacy-coverage --coverage-report coverage/coverage-final.json  # Ensure coverage report is generated
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}  # Use your Codacy project token

    # Step 7: Check for Codacy errors and stop pipeline if errors found
    - name: Check Codacy status and stop if errors found
      run: |
        result=$(curl -sSL https://api.codacy.com/project/{your_project_token}/status)
        if [[ $result == *"error"* ]]; then
          echo "Error found in code quality. Stopping pipeline."
          exit 1
        else
          echo "No error found. Proceeding with pipeline."
        fi
