name: Test Codacy Token

on:
  push:
    branches: [ main ]

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Test Codacy Token
        run: |
          if [ -n "${{ secrets.CODACY_PROJECT_TOKEN }}" ]; then
            echo "Token is set and not empty"
            echo "First few characters: ${CODACY_PROJECT_TOKEN:0:4}..."
          else
            echo "Token is not set or empty"
          fi
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
