name: Node.js CI/CD with Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: true

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Clean Install Dependencies
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm cache clean --force
        npm ci

    - name: Prepare for Analysis
      run: |
        git add .
        git status
        git diff --cached --exit-code || git commit -m "Prepare for analysis" || true

    - name: Run Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        output: results.sarif
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 0
        upload: true
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
