# name: Test Codacy Token

# on:
#   push:
#     branches: [ main ]

# jobs:
#   test-token:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test Codacy Token
#         run: |
#           if [ -n "${{ secrets.CODACY_PROJECT_TOKEN }}" ]; then
#             echo "Token is set and not empty"
#             echo "First few characters: ${CODACY_PROJECT_TOKEN:0:4}..."
#           else
#             echo "Token is not set or empty"
#           fi
#         env:
#           CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

name: Codacy Analysis

on:
  push:
    branches: [ main ]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Debug step to verify environment
      - name: Debug Token Presence
        run: |
          if [ -n "${{ secrets.CODACY_PROJECT_TOKEN }}" ]; then
            echo "Token is present"
          else
            echo "Token is missing"
          fi
        
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4.3.0  # Using specific version
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
