name: Clone Repo on Windows Server

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  clone:
    runs-on: [self-hosted, windows]
    steps:
      - name: Print current directory
        run: |
          echo "Current Directory: $PWD"

      - name: Ensure Git folder exists
        run: |
          New-Item -ItemType Directory -Path "C:\Users\Administrator\Desktop\git folder" -Force

      - name: Clone repository manually
        run: |
          git clone https://github.com/${{ github.repository }} "C:\Users\Administrator\Desktop\git folder"
