name: Clone Repo on Windows Server

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: [self-hosted, windows]
    steps:
      - name: Add Git to PATH
        run: |
          $env:Path += ";C:\Program Files (x86)\Git\cmd"

      - name: Delete old folder if exists
        run: |
          if (Test-Path "C:\Users\Administrator\Desktop\git folder") {
            Remove-Item -Recurse -Force "C:\Users\Administrator\Desktop\git folder"
          }

      - name: Create fresh target folder
        run: |
          New-Item -ItemType Directory -Force -Path "C:\Users\Administrator\Desktop\git folder"

      - name: Clone repository
        run: |
          git clone https://github.com/aakashdeep8530/hello.git "C:\Users\Administrator\Desktop\git folder"
