name: Node.js CI/CD with Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npm install eslint --save-dev

    - name: Create ESLint config
      run: |
        echo 'module.exports = {
          "env": {
            "node": true,
            "es2021": true
          },
          "extends": "eslint:recommended",
          "parserOptions": {
            "ecmaVersion": "latest",
            "sourceType": "module"
          },
          "rules": {
            "indent": ["error", 4],
            "linebreak-style": ["error", "unix"],
            "quotes": ["error", "single"],
            "semi": ["error", "always"]
          }
        }' > .eslintrc.js

    - name: Run Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        output: results.sarif
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 0
        upload: true
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
