name: Node.js CI
# Trigger the workflow when pushing to master or opening pull requests to master
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2
    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change to the Node.js version you prefer, e.g., '14' or '16'
    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install
    # Step 4: Run ESLint to check code quality
    - name: Run ESLint
      run: npm run lint  # Runs "eslint ." as per the script in package.json
