name: Test EC2 Connection

on:
  workflow_dispatch:  # 👈 This enables manual trigger from GitHub UI

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH to Windows EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "✅ Connected to EC2 successfully!"
