name: Node.js CI/CD with Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test || echo "No tests specified"

    - name: Run Codacy Analysis
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      uses: codacy/codacy-analysis-cli-action@master
      with:
        output: results.sarif
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 0

    - name: Upload SARIF results file
      uses: github/codeql-action/upload-sarif@main
      with:
        sarif_file: results.sarif

    - name: Check Codacy Results
      run: |
        if [ -f results.sarif ]; then
          issues=$(cat results.sarif | jq -r '.runs[].results | length')
          if [ "$issues" -gt 0 ]; then
            echo "Found $issues issues in code analysis"
            exit 1
          fi
        fi
