name: Deploy to Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - uat
          - qa
          - preprod
          - prod

jobs:
  deploy:
    runs-on: ${{ github.event_name == 'push' && 'dev-runner' || format('{}-runner', github.event.inputs.environment) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          echo "Running deployment on $RUNNER_NAME"
          # Your deployment commands here
