name: Deploy to Environment

on:
  push:
    branches:
      - test  # Auto-deploy to dev-runner on every push
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - uat
          - qa
          - preprod
          - prod

jobs:
  deploy:
    # Run on dev-runner for push, or specific runner for manual triggers
    runs-on: ${{ github.event_name == 'push' && 'dev-runner' || github.event.inputs.environment + '-runner' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          echo "Deploying on runner: $RUNNER_NAME"
          # Your deployment commands here, for example:
          # ./deploy.sh
