name: Copy Folder and Deploy

on:
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'uat'
        type: choice
        options:
          - dev
          - uat

jobs:
  deploy-dev:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/test') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev') }}
    runs-on: dev-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to dev
        run: |
          SOURCE="."
          DEST="/var/www/html/"
          echo "Deploying to DEV..."
          if [ -d "$DEST" ]; then
            find "$DEST" -mindepth 1 -maxdepth 1 ! -name 'node_modules' -exec rm -rf {} +
          fi
          cp -r "$SOURCE"/* "$DEST"
          echo "✅ Dev deployment successful."

  deploy-uat:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'uat' }}
    runs-on: uat-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to uat
        run: |
          SOURCE="."
          DEST="/var/www/html/"
          echo "Deploying to UAT..."
          if [ -d "$DEST" ]; then
            find "$DEST" -mindepth 1 -maxdepth 1 ! -name 'node_modules' -exec rm -rf {} +
          fi
          cp -r "$SOURCE"/* "$DEST"
          echo "✅ UAT deployment successful."
