name: Copy Folder and Deploy

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  push:               # Trigger on push to test branch (we’ll disable it for uat)
    branches:
      - test

jobs:
  deploy-dev:
    runs-on: dev-runner  # Must be a registered self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy folder to deployment directory on dev
        run: |
          SOURCE="."
          DEST="/var/www/html/" 

          echo "Copying from $SOURCE to $DEST"
          if [ -d "$DEST" ]; then
            echo "Cleaning destination folder, preserving node_modules..."
            # Remove everything except for node_modules
            find "$DEST" -mindepth 1 -maxdepth 1 ! -name 'node_modules' -exec rm -rf {} +
          fi
          cp -r "$SOURCE" "$DEST"
          echo "✅ Folder copied successfully."

  
on:
  workflow_dispatch:
  deploy-uat:
    runs-on: uat-runner  # Must be a registered self-hosted runner
    if: ${{ github.event_name == 'workflow_dispatch' }}  # Trigger only for manual dispatch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy folder to deployment directory on uat
        run: |
          SOURCE="."
          DEST="/var/www/html/" 

          echo "Copying from $SOURCE to $DEST"
          if [ -d "$DEST" ]; then
            echo "Cleaning destination folder, preserving node_modules..."
            # Remove everything except for node_modules
            find "$DEST" -mindepth 1 -maxdepth 1 ! -name 'node_modules' -exec rm -rf {} +
          fi
          cp -r "$SOURCE" "$DEST"
          echo "✅ Folder copied successfully."
